version: '3.3'
services:
    eclipse-mosquitto:
        ports:
            - '1883:1883'
            - '9001:9001'
        volumes:
            - '<DIRECTORY WHERE YOU WANT YOUR MQTT PERSISTED>/config:/mosquitto/config'
            - '<DIRECTORY WHERE YOU WANT YOUR MQTT PERSISTED>/data:/mosquitto/data'
        image: eclipse-mosquitto
